version: '3'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
    driver: local
  nginx_data:
    driver: local
  wordpress_data:
    driver: local
